[workspace]
members = [
  "cli",
  "database",
]

[workspace.dependencies]
anyhow = "1.0.70"
chrono = { version = "0.4.24", default-features = false, features = ["serde"] }
serde = { version = "1.0.160", features = ["derive"] }
tokio = { version = "1.28.2", features = ["macros"] }
