[package]
name = "mailbox"
version = "0.1.0"
authors = ["Caleb Cox"]
edition = "2021"
description = "Message manager for local commands"
readme = "README.md"
repository = "https://github.com/canac/mailbox"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.2.5", features = ["derive"] }
directories = "4.0.1"
rusqlite = { version = "0.27.0", features = ["bundled", "chrono"] }
sea-query = { version = "0.25.2", features = ["attr", "backend-sqlite", "rusqlite", "with-time"] }
