[package]
name = "mailbox"
version = "0.4.0"
authors = ["Caleb Cox"]
edition = "2021"
description = "Message manager for local commands"
readme = "README.md"
repository = "https://github.com/canac/mailbox"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
atty = "0.2.14"
chrono = { version = "0.4.19", features = ["serde"] }
chrono-humanize = "0.2.1"
clap = { version = "3.2.5", features = ["derive"] }
colored = "2.0.0"
crossterm = "0.24.0"
csv = "1.1.6"
directories = "4.0.1"
rusqlite = { version = "0.27.0", features = ["bundled", "chrono"] }
sea-query = { version = "0.25.2", features = ["attr", "backend-sqlite", "rusqlite", "with-time"] }
serde = { version = "1.0.141", features = ["derive"] }
serde_json = "1.0.82"
toml = "0.5.9"
unicode-width = "0.1.9"

[build-dependencies]
clap = { version = "3.2.5", features = ["derive"] }
clap_complete = "3.2.3"
clap_complete_fig = "3.2.4"
clap_mangen = "0.1.10"
