#!/usr/bin/env bash

mailbox archive
mailbox add my-script "Message 1"
mailbox add my-script "Message 2"
mailbox add my-script "Message 3"
mailbox add my-script "Message 4"
mailbox add my-script "Message 5"
mailbox add my-script "Message 6"
mailbox add my-script/mailbox-1 "Message 7"
mailbox add my-script/mailbox-1 "Message 8"
mailbox add my-script/mailbox-1 "Message 9"
mailbox add my-script/mailbox-1 "Message 10"
mailbox add my-script/mailbox-1 "Message 11"
mailbox add my-script/mailbox-1 "Message 12"
mailbox add my-script/mailbox-2 "Message 1"
mailbox add my-script/mailbox-2 "Message 2"
mailbox add my-script/mailbox-2 "Message 3"
mailbox add my-script/mailbox-2 "Message 4"
mailbox add my-script/mailbox-2 "Message 5"
mailbox add my-script/mailbox-2 "Message 6"
mailbox add my-script/mailbox-2 "Message 7"
mailbox add my-script/mailbox-2 "Message 8"
