name: Continuous integration
on: [push, pull_request]

jobs:
  check:
    name: Check (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo check

  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      # neondatabase/create-branch-action and neondatabase/delete-branch-action don't have access to
      # yarn globally-installed commands on Windows without this step
      # https://github.com/neondatabase/create-branch-action/issues/33
      - run: echo "$(yarn global bin)" >> $GITHUB_PATH
        if: ${{ matrix.os }} == 'windows-latest'
        shell: bash
      - uses: neondatabase/create-branch-action@v4
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          parent: test
          branch_name: test-${{ matrix.os }}-$GITHUB_SHA-$GITHUB_REF
          username: ${{ vars.NEON_ROLE }}
          api_key: ${{ secrets.NEON_API_KEY }}
        id: create-branch
      - run: cargo test
        env:
          TEST_DB_URL: ${{ steps.create-branch.outputs.db_url }}
      - uses: neondatabase/delete-branch-action@v3
        if: always()
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch: ${{ steps.create-branch.outputs.branch_id }}
          api_key: ${{ secrets.NEON_API_KEY }}

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - run: cargo clippy -- -D warnings
